/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.co.unad.tallervehicular;

import com.co.unad.tallervehicular.DTO.PropietarioDTO;
import com.co.unad.tallervehicular.DTO.ServicioDTO;
import com.co.unad.tallervehicular.DTO.VehiculoDTO;
import com.co.unad.tallervehicular.controlador.PropietarioControlador;
import com.co.unad.tallervehicular.controlador.ServicioControlador;
import com.co.unad.tallervehicular.controlador.VehiculoControlador;
import com.co.unad.tallervehicular.exceptions.UnadException;
import com.co.unad.tallervehicular.util.ObjectsUtil;
import java.awt.Dimension;
import java.awt.Frame;
import java.math.BigDecimal;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.JOptionPane;

/**
 *
 * @author CARLOS
 */
public class DatosNuevoServicio extends javax.swing.JDialog {

    Frame padre = null;
    ServicioDTO servicio = null;
    ServicioControlador servSvc = new ServicioControlador();
    /**
     * Creates new form VentanaContactos
     */
    public DatosNuevoServicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        inicializarDatos(parent, modal);
        pnlDatos.setPreferredSize(new Dimension(0,350));
        visualizacionBotones();
    }
    public DatosNuevoServicio(java.awt.Frame parent, boolean modal, ServicioDTO servicio) {
        super(parent, modal);
        inicializarDatos(parent, modal);
        this.servicio = servicio;
        visualizacionBotones();
        inputPlaca.setText(servicio.getPlaca());
        inputCedula.setText(servicio.getCedula());
        motivoIngreso.setSelectedItem(servicio.getMotivo_ingreso());
        horasTrabajo.setValue(servicio.getHoras_trabajo());
        fechaIngreso.setValue(servicio.getFecha_ingreso());
        fechaEntrega.setValue(servicio.getFecha_entrega());
        costoServicio.setSelectedItem(servicio.getMotivo_costo_servicio());
    }
    private void inicializarDatos(java.awt.Frame parent, boolean modal){
        padre = parent;
        initComponents();
        setLocationRelativeTo(null);
        agregarItemsMotivoIngreso();
        ajustarSpinnerFechas();
        agregarItemsCostoServicio();
        pnlDatos.setPreferredSize(new Dimension(0,350));
    }
    
    private void visualizacionBotones(){
        btnNuevoVehiculo.setVisible(true);
        btnNuevoPropietario.setVisible(true);
        btnGuardar.setVisible(true);
        btnEliminar.setVisible(false);
        if(servicio != null){
            btnNuevoVehiculo.setVisible(false);
            btnNuevoPropietario.setVisible(false);
            btnGuardar.setText("Actualizar");
            btnGuardar.setVisible(true);
            btnEliminar.setVisible(true);
        }
    }
    
    private void agregarItemsMotivoIngreso(){
        motivoIngreso.removeAllItems();
        String[] nuevasOpciones = {"Mecánica en general", 
        "Cambio de aceite",
        "Alineación y rotación de ruedas",
        "Sistemas de suspensión",
        "Chapa y pintura",
        "Reparación de llantas",
        "Aire acondicionado y calefacción",
        "Servicio de frenos"};

        for (String opcion : nuevasOpciones) {
            motivoIngreso.addItem(opcion);
        }
    }
    private void ajustarSpinnerFechas(){
        Calendar calendar = Calendar.getInstance();
        Date fechaInicial = calendar.getTime();
        calendar.add(Calendar.YEAR, 1);
        Date fechaFinal = calendar.getTime();
        
        SpinnerDateModel modelSpinner = new SpinnerDateModel(fechaInicial, fechaInicial, fechaFinal, Calendar.DAY_OF_MONTH);
        

        fechaIngreso.setModel(modelSpinner);
        fechaIngreso.setEditor(new JSpinner.DateEditor(fechaIngreso, "dd/MM/yyyy"));
        
        fechaEntrega.setModel(modelSpinner);
        fechaEntrega.setEditor(new JSpinner.DateEditor(fechaEntrega, "dd/MM/yyyy"));
        
    }
    private void agregarItemsCostoServicio(){
        costoServicio.removeAllItems();
        String[] nuevasOpciones = {"Mano de obra", "Repuestos"};

        for (String opcion : nuevasOpciones) {
            costoServicio.addItem(opcion);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollpanels = new javax.swing.JScrollPane();
        pnlDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        motivoIngreso = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fechaIngreso = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        fechaEntrega = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        costoServicio = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        horasTrabajo = new javax.swing.JSpinner();
        btnNuevoVehiculo = new javax.swing.JButton();
        inputPlaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        inputCedula = new javax.swing.JTextField();
        btnNuevoPropietario = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 450));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(547, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nuevo Servicio");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Datos Vehiculo");

        jLabel3.setText("Placa:");

        jLabel5.setText("Motivo ingreso:");

        motivoIngreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Datos Servicio");

        jLabel14.setText("Fecha ingreso:");

        jLabel15.setText("Fecha entrega:");

        jLabel16.setText("Costo servicio:");

        costoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel17.setText("Horas trabajo:");

        btnNuevoVehiculo.setText("+ Nuevo Vehiculo");
        btnNuevoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoVehiculoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Datos Propietario");

        jLabel18.setText("Cedula:");

        btnNuevoPropietario.setText("+ Nuevo propietario");
        btnNuevoPropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPropietarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel13)
                                .addComponent(jLabel15)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)))))
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jLabel18)))
                        .addGap(68, 68, 68)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motivoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnNuevoVehiculo))
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNuevoPropietario))
                            .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(costoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horasTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnNuevoVehiculo)
                    .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(motivoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(7, 7, 7)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(inputCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoPropietario))
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(fechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(fechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(costoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(horasTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 247, Short.MAX_VALUE))
        );

        scrollpanels.setViewportView(pnlDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(scrollpanels, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanels, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnGuardar)
                .addGap(61, 61, 61)
                .addComponent(btnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(servicio == null || ObjectsUtil.vacio(servicio.getId())){
            JOptionPane.showMessageDialog(null,"No es posible eliminar este servicio.", "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        servSvc.eliminarServicio(servicio);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try{
            if(!ObjectsUtil.todosConValor(inputPlaca.getText(), inputCedula.getText(), (String)costoServicio.getSelectedItem(), 
                    (Date)fechaIngreso.getValue(), (Date)fechaEntrega.getValue(), (int)horasTrabajo.getValue(), 
                    horasTrabajo.getValue(), (String)motivoIngreso.getSelectedItem())){
                throw new UnadException("Debe rellenar todos los campos.");
            }
            
            PropietarioControlador propSvc = new PropietarioControlador();
            VehiculoControlador vehSvc = new VehiculoControlador();
            VehiculoDTO veh = vehSvc.getVehiculo(inputPlaca.getText());
            if(veh == null){
                throw new UnadException("No se ha encontrado un vehiculo con la placa ingresada.");
            }

            if(!propSvc.cedulaExiste(inputCedula.getText())){
                throw new UnadException("No se ha encontrado un propietario con la cedula ingresada.");
            }
            
            String tipoCosto = (String)costoServicio.getSelectedItem();
            double valorCosto = 0;
            if(tipoCosto.equals("Mano de obra")){

                if(veh.getTipo().equals("Automóvil")){
                    valorCosto = 20_000;
                }else if(veh.getTipo().equals("Camioneta")){
                    valorCosto = 30_000;
                }
            }
            Date fecha_ingreso = (Date)fechaIngreso.getValue();
            Date fecha_entrega = (Date)fechaEntrega.getValue();
            int horas = (int)horasTrabajo.getValue();
            ServicioDTO servBd = new ServicioDTO();
            servBd.setMotivo_ingreso((String)motivoIngreso.getSelectedItem());
            servBd.setFecha_ingreso(fecha_ingreso);
            servBd.setFecha_entrega(fecha_entrega);
            servBd.setCosto(new BigDecimal(valorCosto));
            servBd.setHoras_trabajo(horas);
            servBd.setPlaca(inputPlaca.getText());
            servBd.setCedula(inputCedula.getText());
            servBd.setMotivo_costo_servicio((String)tipoCosto);

            if(servicio != null){
                servBd.setId(servicio.getId());
                servSvc.actualizarServicio(servBd);
            }else{
                servSvc.guardarServicio(servBd);   
            }
        }catch(Exception e){
            if(e instanceof UnadException){
                JOptionPane.showMessageDialog(null,e.getMessage(), "Información", JOptionPane.INFORMATION_MESSAGE);
            }
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private void btnNuevoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoVehiculoActionPerformed
        DatosNuevoVehiculo ventanaP = new DatosNuevoVehiculo(padre, true);
        ventanaP.setVisible(true);
    }//GEN-LAST:event_btnNuevoVehiculoActionPerformed

    private void btnNuevoPropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPropietarioActionPerformed
        DatosNuevoPropietario ventanaP = new DatosNuevoPropietario(padre, true);
        ventanaP.setVisible(true);
    }//GEN-LAST:event_btnNuevoPropietarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosNuevoServicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DatosNuevoServicio dialog = new DatosNuevoServicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevoPropietario;
    private javax.swing.JButton btnNuevoVehiculo;
    private javax.swing.JComboBox<String> costoServicio;
    private javax.swing.JSpinner fechaEntrega;
    private javax.swing.JSpinner fechaIngreso;
    private javax.swing.JSpinner horasTrabajo;
    private javax.swing.JTextField inputCedula;
    private javax.swing.JTextField inputPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> motivoIngreso;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JScrollPane scrollpanels;
    // End of variables declaration//GEN-END:variables
}
